diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=Anandparmar8088
user.email=parmaranand031@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
branch.main.gk-last-accessed=2026-02-02T18:38:03.947Z
branch.main.gk-last-modified=2026-02-02T17:56:03.785Z
branch.B1.gk-last-accessed=2026-02-03T06:02:54.329Z
branch.B1.gk-last-modified=2026-02-02T18:41:31.166Z
branch.B1.remote=origin
branch.B1.merge=refs/heads/B1
branch.B1.vscode-merge-base=origin/main
remote.origin.url=https://github.com/Anandparmar8088/practice-repo.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
